name = "bot-manager"
main = "src/index.js"
compatibility_date = "2024-12-18"

[[kv_namespaces]]
binding = "BOTS_KV"
id = "50eee02191434705833975833bd32f90"

[env.production]
vars = { ENVIRONMENT = "production" }